<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Generator 函数的语法</title>
</head>

<body>
    <script>
        /* 1.简介 */
        /* Generator函数的语法和API
            语法理解:Generator函数是一个状态机,封装了多个内部状态
            执行generator返回一个遍历器对象.generator函数除了状态机,还是一个遍历器对象生成函数.返回的遍历器对象,可以依次遍历generator函数的每一个状态
         */
        /* 形式上generator函数是一个普通函数,两个特征:
           1.function关键字与函数名之间有个*号
           2.函数体内部使用yield表达式,定义不同的内部状态.yield的意思就是产出.
         */
        {
            function* helloWorldGenerator() {
                yield 'hello'
                yield 'world'
                return 'ending'
            }
            var hw = helloWorldGenerator()
            /* generator函数调用之后不执行,返回的也不是函数的运行结果,而是指向内部状态的指针对象,也就是遍历器对象(Iterator Object) */
            /* 下一步,必须调用遍历器对象的next方法,让指针指向下一个状态 
                每次调用next方法,内部指针就从头部函数或上一次停下来的地方开始执行,知道遇到下一个yield或者return语句   
            */
            /* Generator函数是分段执行,yield是暂停执行的标志,next方法可以恢复执行 */
            // console.log(hw.next())
            // {value: "hello", done: false}

            // console.log(hw.next())
            //{ value: "world", done: false }

            // console.log(hw.next())
            //{ value: "ending", done: true }
            //在第三次执行,next方法返回的对象的value属性,紧跟着return语句后面表达式的值(如果没有return语句,则value属性值Wieundefined),done属性为true,表示结束

            // console.log(hw.next())
            //{ value: undefined, done: true }

            /* 从上往下依次执行,每次next都执行一次,value就是当前yield的值,done就是遍历是否执行完成 */
        }
        /* generator函数就返回一个遍历器的对象,代表generator函数的内部指针.每次调用next方法,就会有个有着value和done两个属性的对象返回
            value:当前内部状态的值 yield/return表达式的值
            done:表里是否结束
         */
        {
            /* 声明方式 */
            function* foo1() { }
            function* foo2() { }
            function* foo3() { }
            function* foo4() { }
            /* es6没有规定,因此上面四种方式都可以通过 */
        }

        /* yield表达式 */
        //  generator函数返回的是遍历器对象,调用next方法才会遍历下一个内部状态,提供了可以暂停执行的函数,yield就是暂停的标志
        /* next的运行逻辑
            遇到yield,暂停操作,返回yield后面的值
            下次调用next,再继续往下执行,直到遇到下一个yield
            如果没有遇到新的yield,一直运行到函数结束,直到return语句,并且返回return后面表达式的值 
            如果该函数没有return语句,则返回对象的value为undefined        
         */
        /* yield后面值只有调用next才会执行,js是惰性求值(Lazy Evaluation) */
        {
            function* gen() {
                yield 123 + 456
            }
            let g = gen()
            // console.log(g.next())// 579 false
            // console.log(g.next())// undefined true
        }
        /* yield和return
            相同:返回紧跟着后面的表达式的值
            区别:yield有记忆功能,函数暂停或运行,下次再从该位置继续往后执行
                return没有记忆功能,只能执行一次return,而可以多次执行yield.
            
            generator可以通过yield返回一系列的值,generator--生成器
         */
        /* Generator函数不用yield表大四,成了暂缓执行函数 */
        {
            function* f() {
                console.log('执行了')
            }
            let g = f()
            setTimeout(() => {
                // g.next()
                // 成了暂缓函数
            }, 2000);
        }
        /* 同时 yield表达式只能用在generator函数里面,否则报错 */
        {
            (function () {
                // yield 1
                // error
            })();
        }
        /* 另一种例子 */
        {
            var arr = [1, 2, 3, 4, [8, 9]];
            var flat = function* (a) {
                a.forEach(item => {
                    if (typeof item !== 'number') {
                        // yield * flat(item)
                    } else {
                        // yield item
                        // 报错 forEach方法的参数是一个普通函数,里面不能放yield
                    }
                })
            }
            for (var f of flat(arr)) {
                console.log(f)
            }
        }
        /* 修改后的方法  改用for循环 */
        {
            var arr = [1, 2, 3, 4, [8, 9]];
            var flat = function* (a) {
                for (let i = 0; i < a.length; i++) {
                    const element = a[i];
                    if (typeof element !== 'number') {
                        yield* flat(element)
                    } else {
                        yield element
                    }
                }
            }
            for (var f of flat(arr)) {
                // console.log(f) //1 2 3 4 8 9
            }
        }
        /* 如果yield表达式用在另一个表达式,就需要放在圆括号里面 */
        {
            function* demo() {
                // console.log(1+ yield) //error 
                // console.log(1+ yield 1) /error
                // console.log(1+ (yield))
                // console.log(1+ (yield 1))
            }
            demo()
        }
        /* yield表达式用作函数参数放在赋值表达式右边,可以不加括号 */
        {
            const foo = () => { }
            function* demo() {
                foo(yield 'a', yield 'b');
                let input = yield
            }
        }

        /* 与ITterator 接口的关系 */
        /* 任意一个对象的Symbol.literator方法,等于该对象的遍历器生成函数,
        调用该函数会返回该对象的遍历器对象
            由于Generator函数就是遍历器生成函数,因此可以把generator赋值给对象的symbol.iterator属性,从而使得该对象具有iterator接口
         */
        {
            var myIterator = {};
            myIterator[Symbol.iterator] = function* () {
                yield 1;
                yield 2;
                yield 3;
            }
            // console.log([...myIterator]) // [1,2,3]
            /* generator函数赋值给 Symbol.iterator,从而使得myIterator对象有了Iterator接口,可以被...遍历*/
        }
        /* generator函数执行之后,返回一个遍历器的对象,该对象本身也具有Symbol.iterator属性,执行之后返回自身 */
        {
            function* gen() {
                yield 1
            }
            var g = gen();
            // 执行之后返回自身
            // console.log(g[Symbol.iterator]() === g)
            /* gen是一个Generator函数,调用会生成一个遍历器对象g,g的Symbol.iterator属性也是一个遍历器对象生成函数,执行之后返回自己 */
        }

        /* next方法的参数 */
        /* yield表达式本身没有返回值,或者总是返回undefined.next方法可以带一个参数,该参数会被当做上一个yield表达式的返回值  类似于python生成器的__send__()函数 */
        {
            function* f() {
                for (var i = 0; 1; i++) {
                    var reset = yield i;
                    if (reset) {
                        i = -1;
                        // return
                    }
                }
            }
            var g = f();
            /* 如果没有return语句,一直在for循环循环  那个0是-1加1的加过 */
            // console.log(g.next())//{value: 0, done: false}
            // console.log(g.next())//{value: 1, done: false}
            // console.log(g.next())//{value: 2, done: false}
            // console.log(g.next(true))//{value: 0, done: false}
            // console.log(g.next(true))//{value: 0, done: false}
            // console.log(g.next(true))//{value: 0, done: false}

            /* 如果有return语句,一直在for循环循环  undefined是没有任何返回值的结果 */
            // console.log(g.next())//{value: 0, done: false}
            // console.log(g.next())//{value: 1, done: false}
            // console.log(g.next())//{value: 2, done: false}
            // console.log(g.next(true))//{value: undefined, done: false}
            // console.log(g.next(true))//{value: undefined, done: false}
            // console.log(g.next(true))//{value: undefined, done: false}

            /* 这个功能很有语法意义,generator函数从暂停状态到恢复运行,它的上下文状态(context)是不变的.
            通过next方法的参数,就有办法在generator函数的开始运行之后继续向函数体内部注入值.也就是说,可以在generator
            */
        }
        {
            function* foo(x) {
                var y = 2 * (yield (x + 1))
                var z = yield (y / 3)
                return (x + y + z)
            }
            var a = foo(5)
            // console.log(a.next()) // 6 false
            // console.log(a.next()) // NaN false
            // console.log(a.next()) // NaN false
            var b = foo(5)
            // console.log(b.next()) // 6 false
            // console.log(b.next(12)) // 8 false  --2*12/3
            // console.log(b.next(13)) // 42 false --5+2*12+13
        }
        /* 第一个next传参是无效的,v8会自动忽略,从第二个开始才是有效的 */
        {
            function* dataConsumer() {
                // console.log('started'); //start
                // console.log(`1.${yield}`) // 1.a
                // console.log(`2.${yield}`) // 2.b
                return 'result'
            }
            let genObj = dataConsumer();
            // console.log(genObj.next()) //{value: undefined, done: false}
            // console.log(genObj.next('a')) //{value: undefined, done: false}
            // console.log(genObj.next('b')) //{value: "result", done: true}
            // 在yield要暂停一下,要看yield有没有值
        }
        /* 如果想要在第一次调用next方法时就可以输入值,可以在generator函数外面包一层 */
        {
            function wrapper(generatorFunction) {
                return function (...args) {
                    let generatorObject = generatorFunction(...args);
                    // 相当于先走一步next,下一次next的时候就可以赋值了
                    generatorObject.next();
                    // 返回的是可迭代对象
                    return generatorObject;
                }
            }
            // wrapped其实是里面的匿名函数
            const wrapped = wrapper(function* () {
                console.log(`first input ${yield}`);
                return 'done';
            })
            // console.log(wrapped().next('hello'))
        }

        /* for of 循环 */
        /* for of可以自动遍历Generator函数生成的Iterator对象,而且不需要执行next方法 */
        {
            function* foo() {
                yield 1
                yield 2
                yield 3
                yield 4
                return 5
            }
            a = foo()
            // console.log(a.next())//{value: 1, done: false}
            // console.log(a.next())//{value: 2, done: false}
            // console.log(a.next())//{value: 3, done: false}
            // console.log(a.next())//{value: 4, done: false}
            /*   // 下面done会变为true 就停止执行 */
            // console.log(a.next())//{value: 5, done: true}
            for (const i of foo()) {
                // console.log(i)
                //1 2 3 4
            }
        }
        /* 一旦next方法返回的对象的done属性为true,for of的循环就会终止,而且不返回该对象,所以上面的return的6不在范围内 */
        /* generator函数 + for of实现斐波那契数列 */
        {
            function* fibonacci() {
                let [prev, curr] = [0, 1]
                let count = 0;//轮数
                for (; ;) {
                    count++
                    yield { curr, count };
                    [prev, curr] = [curr, curr + prev]
                }
            }
            for (let n of fibonacci()) {
                if (n.curr > 14) break;
                // console.log(n);
            }
        }
        /* 利用for of循环,可以写出任意对象object的方法,原生的对象没有便利借口,无法使用for of循环.通过generator函数为其增加接口 */
        {
            function* objectEntries(obj) {
                // https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Reflect/ownKeys
                let propsKeys = Reflect.ownKeys(obj);
                for (const propKey of propsKeys) {
                    yield [propsKeys, obj[propsKeys]]
                }
            }
            let jane = {
                first: 'Jane',
                last: 'Doe'
            }
            for (const [key, value] of objectEntries(jane)) {
                // console.log(key, value)
            }
            /* 加上遍历器接口的另一种写法是,将Generator函数加到对象的Symbol.Iterator属性上面 */
        }
        {
            function* objectEntries() {
                let propKeys = Object.keys(this)
                for (const propKey of propKeys) {
                    yield [propKey, this[propKey]]
                }
            }
            let jane = {
                first: 'Jane',
                last: 'Doe'
            }
            jane[Symbol.iterator] = objectEntries;
            for (const [key, value] of jane) {
                // console.log(key, value)
            }
        }
        /* 除了for...of循环,扩展运算符...,解构赋值,Array.from方法内部调用,都是遍历器接口.=>他们都可以将generator函数返回的iterator对象作为参数 */
        {
            function* numbers() {
                yield 1
                yield 2
                return 3
                yield 4
            }
            /* 拓展运算符 */
            // console.log([...numbers()])//[1, 2]
            /* array.from */
            // console.log(Array.from(numbers())) //[1,2]
            /* 解构赋值 */
            let [x, y] = numbers()
            // console.log(x,y) // 1 2
            /* for of */
            for (const n of numbers()) {
                // console.log(n) // 1 2 
            }
        }


        /* Generator.prototype.throw() */
        /* generator函数返回的是遍历器对象,都有一个throw方法.可以在函数体外抛出错误,然后generator函数体内捕获 */
        {
            var g = function* () {
                try {
                    yield
                } catch (e) {
                    console.log('内部捕获', e)
                }
            }
            var i = g()
            i.next()
            try {
                // i.throw(1) // 内部捕获 1
                // i.throw(2) 
            } catch (e) {
                console.log('外部捕获', e)// 外部捕获 2
            }
            /* 第一个内部捕获是throw 1 的时候内部的捕获,第二个throw,因为generator函数内部的catch已经执行过了,不会再捕捉错误了 因此被函数体外的catch捕获 */
        }
        {
            /* throw方法可以接受一个参数,该参数会被catch语句接收,建议抛出error实例 */
            var g = function* () {
                try {
                    yield
                } catch (error) {
                    console.log(error)
                }
            }
            var i = g()
            i.next()
            // i.throw(new Error('出错了'))
        }
        /* 不要混淆遍历器对象的throw方法和全局的throw命令. 用遍历器对象的throw方法,而不是用全局的throw命令,因为全局的只能被函数体外的catch捕获*/
        {
            var g = function* () {
                try {
                    yield
                } catch (e) {
                    if (e != 'a') throw e;
                    console.log('内部捕获', e);
                }
            }
            var i = g()
            i.next()
            try {
                throw new Error('a')
                throw new Error('b')
            } catch (error) {
                // console.log('外部捕获', error)// 外部捕获
            }
        }
        /* throw方法抛出的错误要被内部捕获,前提是至少执行过一次next */
        {
            var g = function* () {
                try {
                    yield
                } catch (error) {
                    console.log(error)
                }
            }
            var i = g()
            // i.throw(1) // Uncaught 1
            /* 没有next,generator函数还没有开始执行,这是throw的方法跑错只可能在函数外部 */
        }
        /* throw方法调用会附带执行吓一条yield表达式,就是会执行一次next方法 */
        {
            var g = function* () {
                try {
                    yield console.log('a')
                } catch (error) {
                    console.error(error)
                }
                yield console.log('b')
                yield console.log('c')
            }
            var g = g()
            // g.next() //a 
            // g.throw(1) // 1 b
            // g.next() //c
            /* 只要Generator函数内部部署了trycatch代码块,遍历器的throw方法抛出错误,并不影响下一次遍历 */
        }
        /* throw 和g.throw是无关的 */
        {
            var g = function* () {
                // yield console.log('hello')
                // yield console.log('world')
            }
            var g = g()
            g.next();
            try {
                throw 1
            } catch (error) {
                g.next()
            }
            // hello
            // world
        }
        /* 多个yield表达式,可以只用一个trycatch代码来捕获.如果使用回调函数就要为每个函数内部写一个错误处理程序,现在在generator内部写一个trycatch */

        /* generator函数体外抛出的错误可以在函数体内部捕获,反过来,generator函数体内抛出的错误,也可以被函数体外的catch捕获 */
        {
            function* foo() {
                var x = yield 3;
                var y = x.toUpperCase()
                yield y
            }
            var it = foo()
            it.next() // 3 false
            try {
                it.next(1)
            } catch (error) {
                // console.log(error)
                //TypeError: x.toUpperCase is not a function
            }
        }
        /* 如果generator过程中拋出了错误,并且没有被内部捕获,就不会再执行下去了.如果此后还调用next方法,将返回一个 {value:undefined,done:true}.js引擎默认认为generator已经结束 */
        {
            function* g() {
                yield 1
                console.log('throw an exception')
                throw new Error('generator broke')
                yield 2
                yield 3

            }
            function log(generator) {
                var v;
                console.log('starting generator') //starting generator
                try {
                    v = generator.next()
                    console.log('第1次运行next方法', v)//{value: 1, done: false}
                } catch (error) {
                    console.log('捕捉错误', v)
                }
                try {
                    v = generator.next() //starting generator ->抛出错误
                    console.log('第2次运行next方法', v)
                } catch (error) {
                    console.log('捕捉错误', v)// 捕捉错误 {value: 1, done: false}
                }
                try {
                    v = generator.next()
                    console.log('第3次运行next方法', v)//第3次运行next方法 {value: undefined, done: true}
                } catch (error) {
                    console.log('捕捉错误', v)
                }
                console.log('caller done')// caller done
            }
            // log(g())
            /* 执行三次next方法,第二次抛出错误,返回undefined true.结束generator */
        }

        /* generator.prototype.return() */
        /* generator函数返回的遍历器对象,还有一个return方法,可以返回给定的值,并且结束generator函数 */
        {
            function* gen() {
                yield 1;
                yield 2;
                yield 3;
            }
            var g = gen();
            // console.log(g.next()) // {value:1,done:false}
            // console.log(g.return()) // {value:undefined,done:true}
            // console.log(g.return(6)) // {value:6,done:true}
            // console.log(g.next()) // {value:undefined,done:true}
            /* return 不提供参数的话就返回undefined,而且后续的done都是true */
        }
        /* 如果Generator内部函数有try...finally代码块,namereturn方法会推迟到finally代码块再执行 */
        {
            function* numbers() {
                yield 1
                try {
                    yield 2
                    yield 3
                } finally {
                    yield 4
                    yield 5
                }
                yield 6
            }
            var g = numbers();
            // console.log(g.next()) //{value:1,done:false}
            // console.log(g.next())//{value:2,done:false}
            // console.log(g.return(7))//{value:4,done:false}
            // console.log(g.next())//{value:5,done:false}
            // console.log(g.next())//{value:7,done:true}
            /* 上述代码中,调用return方法后,就开始执行finally代码块,然后等到finally代码块执行完成再执行return方法 */
        }

        /* next throw return的共同点 */
        /* 这三个方法本质上是同一件事,作用都是让Generator函数恢复执行,并且使用不同的语句替换掉yield表达式 */
        /* next是将yield表达式替换成一个值 */
        {
            const g = function* (x, y) {
                let result = yield x + y
                return result
            }
            const gen = g(1, 2)
            // console.log(gen.next()) // {value: 3, done: false}
            // console.log(gen.next(1)) // {value: 1, done: true}
        }
        /* throw就是将yield表达式替换成了一个throw语句 */
        {
            {
                const g = function* (x, y) {
                    let result = yield x + y
                    return result
                }
                const gen = g(1, 2)
                // gen.throw(new Error('出错了'))//Uncaught Error: 出错了
                /* 相当于:将let ressult=yield x+y 替换成let result=new Error('出错了') */
            }
        }
        /* return是将yield表达式替换成一个throw语句 */
        {
            const g = function* (x, y) {
                let result = yield x + y
                return result
            }
            const gen = g(1, 2)
            // console.log(gen.return(12)) // {value: 12, done: true}
            /* 相当于将let result=yield x+y =>替换成let result=return 2  */
        }

        /* yield* 表达式 */
    </script>
</body>

</html>
